name: Publish

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: gradle
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
          
    - name: Build artifacts
      run: ./gradlew build
      
    - uses: Kir-Antipov/mc-publish@v3.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
